### ISSUE TITLE
Clarify Field.name in relation to the RFC

### ISSUE THREAD

**Issue by jaysonsantos** [rousan/multer-rs#51]
Hi there, this is not a bug per se but, I would like to clarify the function [Field.name()](https://docs.rs/multer/latest/src/multer/field.rs.html#83-85) which returns an option but, on the [pointed doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#as_a_header_for_a_multipart_body) it says that for a header for multipart body it is mandatory. The question is, on multer is it optional because can be used to represent both the multipart body's and the HTTP headers?

**Comment by SergioBenitez** [comment]
No, I don't think that's why. This library tries to strike a good balance between faithfully following the spec while also being aware of what happens in the real world to ensure applications using `multer` actually work in the wild. It's not unheard of for clients to sent fields without field names, and so outright rejecting such fields would mean not functioning with that class of clients. In that case the field would be `None`, of course. What's more, this allows applications to choose whether to reject fields without names (such as Rocket does) or not by simply filtering out fields without `name.is_none()`.
